### ISSUE TITLE
No support for the face `:extend` attribute.

### ISSUE THREAD

**Issue by ideasman42** [hniksic/emacs-htmlize#37]
This comparison shows emacs 29 (current git) with ediff that uses `ediff-odd-diff-A` facek which defaults to:

```
Face: ediff-odd-diff-A (sample) (customize this face)

Documentation:
Face for highlighting odd-numbered non-current differences in buffer A.

Defined in ‘ediff-init.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: #3e3e5e
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: t
          Inherit: unspecified
```

-----

Screenshot of emacs/html compared.
![extend_unsupported](https://user-images.githubusercontent.com/1869379/137583356-e6f20431-5b5a-4acf-897e-30965af53276.jpg)
